### ISSUE TITLE
You're actually hurting people with this repo

### ISSUE THREAD

**Issue by sheenarbw** [Scottburg/coderbyte_solutions#1]
I work for a non profit educaton provider that trains developers in Africa.  We use Coderbyte tests to keep track of certain skills. When students fails a test then they get allocated extra help and support so that they can master the skills.  Some students have managed to find this resource so they can cheat on their tests because they dont know yet that we are here to help them, they think failing will get them kicked out. Reps like this make it very hard to seee who actually needs assistance.

It's quite bad that this exists. It reduces the effectiveness of people who are willing to put time into teaching and growing others.

**Comment by Scottburg** [comment]
Hi there, sure I can make this private to restrict access.
